### ISSUE TITLE
Issue with valid card number (according to Luhn) but unknown vendor

### ISSUE THREAD

**Issue by intrueder** [Andriy1236/Completed-tasks-for-Kottans.org-Free-Csharp-course-in-Lviv#4]
Vendor for `35301113333000001` has been recognized as `Unknown` (correct, 17 digits instead of 16 for JCB)
I think, that such number should not pass validation, but it passes.

**Comment by Andriy1236** [comment]
I am so sorry,  but i don't understand. Kottans gave some link(https://en.wikipedia.org/wiki/Bank_card_number). In this link we can see that JCB card must have 16 numbers. What's wrong? I need to change condition or not?

**Comment by intrueder** [comment]
Right, JCB card must have 16 digits. And when I pass number with 17 digits it method `GetCreditCardVendor` returns "Unknown", which is correct. The problem is with `IsCreditCardNumberValid` method, it returns `true` for this number, but I expect `false`.

**Comment by Andriy1236** [comment]
Sorry, but why you expect false? 
In IsCreditCardNumberValid:
 1)reverse input data.
 2)all even numbers i * 2.
 3)if some  even number >9 i add 2 numbers(number = 10 and 10 > 9 and number = 1+0)
 4)I add all numbers  in lambda (Sum(x => x)  and  check result  (Sum(x => x) % 10 == 0))
 if  Sum(x => x) % 10 is 0  return true else false

Step by step with example:
we have 35301113333000001
1)reverse = 10000033331110353
2) *2 all even numbers =  1,0,0,0,0,0,3,6,3,6,1,2,1,0,3,10,3
3)we can see 10. 10 >9, that's why our number 1+0=1
4)finaly we have 1,0,0,0,0,0,3,6,3,6,1,2,1,0,3,1,3
5)we add all numbers 1+3+6+3+6+1+2+1+3+1+3 = 30
6)30%10 = 0  that's why true

program understand that our example is valid but it don't know what type of vendor has our example.
Maybe my Luhn algorithm is wrong???

**Comment by intrueder** [comment]
Everything is ok with Luhn algorithm, but it is not enough. Luhn algorithm has wide application, but in our tasks we should use it to check **credit card numbers** only. `35301113333000001` does not look as credit card number, because there is no vendor for it. It is just a **digit series** that is valid according to Luhn algorithm, but it is not valid **card number**.

**Comment by Andriy1236** [comment]
Ok,I have understood this Idea.I used giant "if" in GetCreditCardVendor to solve this problem.I know, this is bad way, but I don't know regular expression((( I rewrote my code.

**Comment by intrueder** [comment]
still reproducable

**Comment by Andriy1236** [comment]
Fixes #4
Ok. I did commit but something went wrong. I rewrote IsCreditCardNumberValid. It contains some new condition. If input card number begins with the "right" numbers, but it has wrong length, the fuction will generate exeption.

**Comment by intrueder** [comment]
But why exception? :) it was correct to return "Unknown" from `GetCreditCardVendor`, now the behavior is broken...

**Comment by Andriy1236** [comment]
Fixes #4
Ok. I rewrote  my code again))). I I removed exeption, but i added simple event. Now the behavior is fine and user will receive message if he writes non bank card number. I changed  BankCard.cs and Program.cs
